# -*- coding: utf-8 -*-
"""Build Interactive LLM Agents

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ns61t4h_yi9BXhTkTFomCm2a6XAoAjs

# **Build Interactive LLM Agents with Tools**

----

### Installing Required Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip uninstall -y langchain langchain-openai langchain-ibm langchain-core
# %pip install langchain langchain-openai langchain-ibm

# Commented out IPython magic to ensure Python compatibility.
# %pip install langchain-ibm | tail -n 1

from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, ToolMessage

"""### Set up OpenAI API Key

1.  **Get an OpenAI API key**: If you don't have one, create an account and generate an API key from the [OpenAI platform](https://platform.openai.com/account/api-keys).
2.  **Add to Colab Secrets**: In Google Colab, click on the "🔑" (Secrets) icon in the left panel. Add a new secret with the name `OPENAI_API_KEY` and paste your API key as the value.
3.  **Enable Notebook access**: Make sure to toggle on "Notebook access" for this secret.
"""

from google.colab import userdata
userdata.get('OPENAI_API_KEY')

# Import the userdata module from google.colab
from google.colab import userdata

# Retrieve the API key from Colab secrets
OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')

# Set the API key as an environment variable (Langchain automatically picks it up)
import os
os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY

print("OpenAI API key loaded successfully!")

from langchain.chat_models import init_chat_model

llm = init_chat_model("gpt-4o-mini", model_provider="openai")

"""Creating Custom Tools with LangChain"""

@tool
def add(a: int, b: int) -> int:
    """
    Add a and b.

    Args:
        a (int): first integer to be added
        b (int): second integer to be added

    Return:
        int: sum of a and b
    """
    return a + b

"""### Add tools to the LLM"""

tools = [add]

llm_with_tools = llm.bind_tools(tools)

"""Create more tools"""

@tool
def subtract(a: int, b:int) -> int:
    """Subtract b from a."""
    return a - b

@tool
def multiply(a: int, b:int) -> int:
    """Multiply a and b."""
    return a * b

"""Testing the functions

"""

tool_map = {
    "add": add,
    "subtract": subtract,
    "multiply": multiply
}

input_ = {
    "a": 1,
    "b": 2
}

tool_map["add"].invoke(input_)

"""Add new tools to LLM"""

tools = [add, subtract, multiply]

llm_with_tools = llm.bind_tools(tools)

"""## Interacting with the Model

Craft the user query
"""

query = "What is 3 + 2?"
chat_history = [HumanMessage(content=query)]

"""Invoke the model"""

response_1 = llm_with_tools.invoke(chat_history)
chat_history.append(response_1)

print(type(response_1))
#print(response_1)

"""Parse tool calls"""

tool_calls_1 = response_1.tool_calls

tool_1_name = tool_calls_1[0]["name"]
tool_1_args = tool_calls_1[0]["args"]
tool_call_1_id = tool_calls_1[0]["id"]

print(f'tool name:\n{tool_1_name}')
print(f'tool args:\n{tool_1_args}')
print(f'tool call ID:\n{tool_call_1_id}')

"""Invoke the Tool"""

tool_response = tool_map[tool_1_name].invoke(tool_1_args)
tool_message = ToolMessage(content=tool_response, tool_call_id=tool_call_1_id)

print(tool_message)

chat_history.append(tool_message)

"""### Generate a final answer from chat history

"""

answer = llm_with_tools.invoke(chat_history)
print(type(answer))
print(answer.content)

"""## Building an Agent

"""

class ToolCallingAgent:
    def __init__(self, llm):
        self.llm_with_tools = llm.bind_tools(tools)
        self.tool_map = tool_map

    def run(self, query: str) -> str:
        # Step 1: Initial user message
        chat_history = [HumanMessage(content=query)]

        # Step 2: LLM chooses tool
        response = self.llm_with_tools.invoke(chat_history)
        if not response.tool_calls:
            return response.contet # Direct response, no tool needed
        # Step 3: Handle first tool call
        tool_call = response.tool_calls[0]
        tool_name = tool_call["name"]
        tool_args = tool_call["args"]
        tool_call_id = tool_call["id"]

        # Step 4: Call tool manually
        tool_result = self.tool_map[tool_name].invoke(tool_args)

        # Step 5: Send result back to LLM
        tool_message = ToolMessage(content=str(tool_result), tool_call_id=tool_call_id)
        chat_history.extend([response, tool_message])

        # Step 6: Final LLM result
        final_response = self.llm_with_tools.invoke(chat_history)
        return final_response.content

my_agent = ToolCallingAgent(llm)

print(my_agent.run("one plus 2"))

print(my_agent.run("one - 2"))

print(my_agent.run("three times two"))